declare const tag: unique symbol;

type Tagged<Type, TagName extends PropertyKey> = Type & {
  readonly [tag]: { [K in TagName]: never };
};

type Datetime = Tagged<string, 'DateTime'>;
type Integer = Tagged<number, 'Int'>;
type Float = Tagged<number, 'Float'>;
type Uri = Tagged<string, 'Uri'>;

type Maybe<T> = T | null | undefined;

export type Team = {
  abbreviation: Maybe<string>;
  alias: Maybe<string>;
  createdAt: Datetime;
  id: Integer;
  league: Maybe<string>;
  logo: Maybe<string>;
  name: Maybe<string>;
  providerId: Maybe<string>;
  record: Maybe<string>;
  updatedAt: Datetime;
};

export type Sport = {
  image: Uri;
  ordering: string;
  resolution: Uri;
  series: string;
  sport: string;
  tags: string;
};

export type Tag = {
  createdAt: Datetime;
  createdBy: Maybe<Integer>;
  forceHide: Maybe<boolean>;
  forceShow: Maybe<boolean>;
  id: string;
  isCarousel: Maybe<boolean>;
  label: Maybe<string>;
  publishedAt: Maybe<string>;
  slug: Maybe<string>;
  updatedAt: Datetime;
  updatedBy: Maybe<Integer>;
};

export type ImageOptimized = {
  field: Maybe<string>;
  id: string;
  imageOptimizedComplete: Maybe<boolean>;
  imageOptimizedLastUpdated: Maybe<string>;
  imageSizeKbOptimized: Maybe<Float>;
  imageSizeKbSource: Maybe<Float>;
  imageUrlOptimized: Maybe<string>;
  imageUrlSource: Maybe<string>;
  relId: Maybe<Integer>;
  relname: Maybe<string>;
};

export type Event = {
  active: Maybe<boolean>;
  archived: Maybe<boolean>;
  automaticallyActive: Maybe<boolean>;
  automaticallyResolved: Maybe<boolean>;
  cantEstimate: Maybe<boolean>;
  carouselMap: Maybe<string>;
  categories: Array<Category>;
  category: Maybe<string>;
  chats: Array<Chat>;
  closed: Maybe<boolean>;
  closedTime: Maybe<Datetime>;
  collections: Array<Collection>;
  commentCount: Maybe<Integer>;
  color: Maybe<string>;
  commentsEnabled: Maybe<boolean>;
  competitive: Maybe<Float>;
  countryName: Maybe<string>;
  createdAt: Datetime;
  createdBy: Maybe<string>;
  creationDate: Maybe<Datetime>;
  cyom: Maybe<boolean>;
  deploying: Maybe<boolean>;
  deployingTimestamp: Maybe<Datetime>;
  description: Maybe<string>;
  disqusThread: Maybe<string>;
  elapsed: Maybe<string>;
  electionType: Maybe<string>;
  enableNegRisk: Maybe<boolean>;
  enableOrderBook: Maybe<boolean>;
  endDate: Maybe<Datetime>;
  ended: Maybe<boolean>;
  estimateValue: Maybe<boolean>;
  estimatedValue: Maybe<string>;
  eventCreators: Array<EventCreator>;
  eventDate: Maybe<string>;
  eventWeek: Maybe<Integer>;
  featured: Maybe<boolean>;
  featuredImage: Maybe<string>;
  featuredImageOptimized: Maybe<ImageOptimized>;
  featuredOrder: Maybe<Integer>;
  finishedTimestamp: Maybe<Datetime>;
  gameId: Maybe<Float>;
  gameStatus: Maybe<string>;
  gmpChartMode: Maybe<string>;
  icon: Maybe<string>;
  iconOptimized: Maybe<ImageOptimized>;
  id: string;
  image: Maybe<string>;
  imageOptimized: Maybe<ImageOptimized>;
  isTemplate: Maybe<boolean>;
  liquidity: Maybe<Float>;
  liquidityAmm: Maybe<Float>;
  liquidityClob: Maybe<Float>;
  live: Maybe<boolean>;
  markets: Array<Market>;
  negRisk: Maybe<boolean>;
  negRiskAugmented: Maybe<boolean>;
  negRiskFeeBips: Maybe<Float>;
  negRiskMarketID: Maybe<string>;
  new: Maybe<boolean>;
  openInterest: Maybe<Float>;
  parentEvent: Maybe<string>;
  parentEventId: Maybe<Float>;
  pendingDeployment: Maybe<boolean>;
  period: Maybe<string>;
  published_at: Maybe<string>;
  resolutionSource: Maybe<string>;
  restricted: Maybe<boolean>;
  scheduledDeploymentTimestamp: Maybe<Datetime>;
  score: Maybe<string>;
  series: Array<Serie>;
  seriesSlug: Maybe<string>;
  showAllOutcomes: Maybe<boolean>;
  showMarketImages: Maybe<boolean>;
  slug: string;
  sortBy: Maybe<string>;
  spreadsMainLine: Maybe<Float>;
  startDate: Maybe<Datetime>;
  startTime: Maybe<Datetime>;
  subEvents: Maybe<Array<string>>;
  subcategory: Maybe<string>;
  subtitle: Maybe<string>;
  tags: Array<Tag>;
  templateVariables: Maybe<string>;
  templates: Array<Template>;
  ticker: Maybe<string>;
  title: string;
  totalsMainLine: Maybe<Float>;
  tweetCount: Maybe<Integer>;
  updatedAt: Datetime;
  updatedBy: Maybe<string>;
  volume1mo: Maybe<Float>;
  volume1wk: Maybe<Float>;
  volume1yr: Maybe<Float>;
  volume24hr: Maybe<Float>;
  volume: Maybe<Float>;
};

export type Market = {
  acceptingOrders: Maybe<boolean>;
  acceptingOrdersTimestamp: Maybe<Datetime>;
  active: Maybe<boolean>;
  ammType: Maybe<string>;
  approved: Maybe<boolean>;
  archived: Maybe<boolean>;
  automaticallyActive: Maybe<boolean>;
  automaticallyResolved: Maybe<boolean>;
  bestAsk: Maybe<Float>;
  bestBid: Maybe<Float>;
  categories: Array<Category>;
  category: Maybe<string>;
  categoryMailchimpTag: Maybe<string>;
  chartColor: Maybe<string>;
  clearBookOnStart: Maybe<boolean>;
  clobRewards: Maybe<Array<ClobReward>>;
  clobTokenIds: Maybe<string>;
  closed: Maybe<boolean>;
  closedTime: Maybe<string>;
  commentsEnabled: Maybe<boolean>;
  competitive: Maybe<Float>;
  conditionId: string;
  createdAt: Datetime;
  createdBy: Maybe<Float>;
  creator: Maybe<string>;
  curationOrder: Maybe<Integer>;
  customLiveness: Maybe<Integer>;
  cyom: Maybe<boolean>;
  denominationToken: Maybe<string>;
  deploying: Maybe<boolean>;
  deployingTimestamp: Maybe<Datetime>;
  description: Maybe<string>;
  disqusThread: Maybe<string>;
  enableOrderBook: Maybe<boolean>;
  endDate: Maybe<Datetime>;
  endDateIso: Maybe<string>;
  eventStartTime: Maybe<Datetime>;
  events: Array<Event>;
  featured: Maybe<boolean>;
  fee: Maybe<string>;
  feesEnabled: Maybe<boolean>;
  formatType: Maybe<string>;
  fpmmLive: Maybe<boolean>;
  funded: Maybe<boolean>;
  fundedTimestamp: Maybe<Datetime>;
  gameId: Maybe<string>;
  gameStartTime: Maybe<string>;
  groupItemRange: Maybe<string>;
  groupItemThreshold: Maybe<string>;
  groupItemTitle: Maybe<string>;
  hasReviewedDates: Maybe<boolean>;
  holdingRewardsEnabled: Maybe<boolean>;
  icon: Maybe<string>;
  iconOptimized: Maybe<ImageOptimized>;
  id: string;
  image: Maybe<string>;
  imageOptimized: Maybe<ImageOptimized>;
  lastTradePrice: Maybe<Float>;
  line: Maybe<Float>;
  liquidity: Maybe<string>;
  liquidityAmm: Maybe<Float>;
  liquidityClob: Maybe<Float>;
  liquidityNum: Maybe<Float>;
  lowerBound: Maybe<string>;
  lowerBoundDate: Maybe<string>;
  mailchimpTag: Maybe<string>;
  makerBaseFee: Maybe<Integer>;
  manualActivation: Maybe<boolean>;
  marketGroup: Maybe<Integer>;
  marketMakerAddress: Maybe<string>;
  marketType: Maybe<string>;
  negRisk: Maybe<boolean>;
  negRiskMarketID: Maybe<string>;
  negRiskOther: Maybe<boolean>;
  negRiskRequestID: Maybe<string>;
  new: Maybe<boolean>;
  notificationsEnabled: Maybe<boolean>;
  oneDayPriceChange: Maybe<Float>;
  oneHourPriceChange: Maybe<Float>;
  oneMonthPriceChange: Maybe<Float>;
  oneWeekPriceChange: Maybe<Float>;
  oneYearPriceChange: Maybe<Float>;
  orderMinSize: Maybe<Float>;
  orderPriceMinTickSize: Maybe<Float>;
  outcomePrices: Maybe<string>;
  outcomes: Maybe<string>;
  pagerDutyNotificationEnabled: Maybe<boolean>;
  pastSlugs: Maybe<string>;
  pendingDeployment: Maybe<boolean>;
  question: string;
  questionID: Maybe<string>;
  ready: Maybe<boolean>;
  readyForCron: Maybe<boolean>;
  readyTimestamp: Maybe<Datetime>;
  resolutionSource: Maybe<string>;
  resolvedBy: Maybe<string>;
  restricted: Maybe<boolean>;
  rewardsMaxSpread: Maybe<Float>;
  rewardsMinSize: Maybe<Float>;
  rfqEnabled: Maybe<boolean>;
  scheduledDeploymentTimestamp: Maybe<Datetime>;
  score: Maybe<Integer>;
  secondsDelay: Maybe<Integer>;
  sentDiscord: Maybe<boolean>;
  seriesColor: Maybe<string>;
  shortOutcomes: Maybe<string>;
  showGmpOutcome: Maybe<boolean>;
  showGmpSeries: Maybe<boolean>;
  slug: string;
  sponsorImage: Maybe<string>;
  sponsorName: Maybe<string>;
  sportsMarketType: Maybe<string>;
  spread: Maybe<Float>;
  startDate: Maybe<Datetime>;
  startDateIso: Maybe<string>;
  subcategory: Maybe<string>;
  submitted_by: Maybe<string>;
  tags: Array<Tag>;
  takerBaseFee: Maybe<Float>;
  takerBaseFee: Maybe<Integer>;
  teamAID: Maybe<string>;
  teamBID: Maybe<string>;
  twitterCardImage: Maybe<string>;
  twitterCardLastRefreshed: Maybe<string>;
  twitterCardLastValidated: Maybe<string>;
  twitterCardLocation: Maybe<string>;
  umaBond: Maybe<string>;
  umaEndDate: Maybe<string>;
  umaEndDateIso: Maybe<string>;
  umaResolutionStatus: Maybe<string>;
  umaResolutionStatuses: Maybe<string>;
  umaReward: Maybe<string>;
  updatedAt: Datetime;
  updatedBy: Maybe<Float>;
  upperBound: Maybe<string>;
  upperBoundDate: Maybe<string>;
  volume1mo: Maybe<Float>;
  volume1moAmm: Maybe<Float>;
  volume1moClob: Maybe<Float>;
  volume1wk: Maybe<Float>;
  volume1wkAmm: Maybe<Float>;
  volume1wkClob: Maybe<Float>;
  volume1yr: Maybe<Float>;
  volume1yrAmm: Maybe<Float>;
  volume1yrClob: Maybe<Float>;
  volume24hr: Maybe<Float>;
  volume24hrAmm: Maybe<Float>;
  volume24hrClob: Maybe<Float>;
  volume: Maybe<string>;
  volumeAmm: Maybe<Float>;
  volumeClob: Maybe<Float>;
  volumeNum: Maybe<Float>;
  wideFormat: Maybe<boolean>;
  xAxisValue: Maybe<string>;
  yAxisValue: Maybe<string>;
};

export type Serie = {
  active: Maybe<boolean>;
  archived: Maybe<boolean>;
  categories: Array<Category>;
  cgAssetName: Maybe<string>;
  chats: Array<Chat>;
  closed: Maybe<boolean>;
  collections: Array<Collection>;
  commentCount: Maybe<Integer>;
  commentsEnabled: Maybe<boolean>;
  competitive: Maybe<string>;
  createdAt: Datetime;
  createdBy: Maybe<string>;
  description: Maybe<string>;
  events: Array<Event>;
  featured: Maybe<boolean>;
  icon: Maybe<string>;
  id: string;
  image: Maybe<string>;
  isTemplate: Maybe<boolean>;
  layout: Maybe<string>;
  liquidity: Maybe<Float>;
  new: Maybe<boolean>;
  publishedAt: Maybe<string>;
  pythTokenID: Maybe<string>;
  recurrence: Maybe<string>;
  restricted: Maybe<boolean>;
  score: Maybe<Integer>;
  seriesType: Maybe<string>;
  slug: Maybe<string>;
  startDate: Maybe<Datetime>;
  subtitle: Maybe<string>;
  tags: Array<Tag>;
  templateVariables: Maybe<boolean>;
  ticker: Maybe<string>;
  title: Maybe<string>;
  updatedAt: Datetime;
  updatedBy: Maybe<string>;
  volume24hr: Maybe<Float>;
  volume: Maybe<Float>;
};

export type Comment = {
  body: Maybe<string>;
  createdAt: Datetime;
  id: string;
  parentCommentID: Maybe<string>;
  parentEntityID: Maybe<Integer>;
  parentEntityType: Maybe<string>;
  profile: Profile;
  reactionCount: Maybe<Integer>;
  reactions: Array<Reaction>;
  replyAddress: Maybe<string>;
  reportCount: Maybe<Integer>;
  updatedAt: Datetime;
  userAddress: Maybe<string>;
};

export type Activity = {
  asset: Maybe<string>;
  bio: Maybe<string>;
  conditionId: `0x${string}`;
  eventSlug: Maybe<string>;
  icon: Maybe<string>;
  name: Maybe<string>;
  outcome: Maybe<string>;
  outcomeIndex: Maybe<Integer>;
  price: Maybe<Float>;
  profileImage: Maybe<string>;
  profileImageOptimized: Maybe<string>;
  proxyWallet: `0x${string}`;
  pseudonym: Maybe<string>;
  side: 'BUY' | 'SELL';
  size: Maybe<Float>;
  slug: Maybe<string>;
  timestamp: Maybe<Integer>;
  title: Maybe<string>;
  transactionHash: Maybe<string>;
  type: 'TRADE' | 'SPLIT' | 'MERGE' | 'REDEEM' | 'REWARD' | 'CONVERSION';
  usdcSize: Maybe<Float>;
};

export type Trade = {
  asset: Maybe<string>;
  bio: Maybe<string>;
  conditionId: `0x${string}`;
  eventSlug: string;
  icon: Maybe<string>;
  name: Maybe<string>;
  outcome: Maybe<string>;
  outcomeIndex: Maybe<Integer>;
  price: Float;
  profileImage: Maybe<string>;
  profileImageOptimized: Maybe<string>;
  proxyWallet: `0x${string}`;
  pseudonym: Maybe<string>;
  side: 'BUY' | 'SELL';
  size: Float;
  slug: Maybe<string>;
  timestamp: Integer;
  title: Maybe<string>;
  transactionHash: Maybe<string>;
  transactionHash: string;
};

export type Category = {
  createdAt: Datetime;
  createdBy: Maybe<string>;
  id: string;
  label: Maybe<string>;
  parentCategory: Maybe<string>;
  publishedAt: Maybe<string>;
  slug: Maybe<string>;
  updatedAt: Datetime;
  updatedBy: Maybe<string>;
};

export type Profile = {
  baseAddress: Maybe<string>;
  bio: Maybe<string>;
  displayUsernamePublic: Maybe<boolean>;
  isCreator: Maybe<boolean>;
  isMod: Maybe<boolean>;
  name: Maybe<string>;
  positions: Array<Position>;
  profileImage: Maybe<string>;
  profileImageOptimized: Maybe<ImageOptimized>;
  proxyWallet: Maybe<string>;
  pseudonym: Maybe<string>;
};

export type Position = {
  tokenId: Maybe<string>;
  positionSize: Maybe<string>;
};

export type Reaction = {
  id: string;
  commentID: Maybe<Integer>;
  reactionType: Maybe<string>;
  icon: Maybe<string>;
  userAddress: Maybe<string>;
  createdAt: Datetime;
  profile: Profile;
};

export type Chat = {
  id: string;
  channelId: Maybe<string>;
  channelName: Maybe<string>;
  channelImage: Maybe<string>;
  live: Maybe<boolean>;
  startTime: Maybe<Datetime>;
  endTime: Maybe<Datetime>;
};

export type Collection = {
  id: string;
  ticker: Maybe<string>;
  slug: Maybe<string>;
  title: Maybe<string>;
  subtitle: Maybe<string>;
  collectionType: Maybe<string>;
  description: Maybe<string>;
  tags: Maybe<string>;
  image: Maybe<string>;
  icon: Maybe<string>;
  headerImage: Maybe<string>;
  layout: Maybe<string>;
  active: Maybe<boolean>;
  closed: Maybe<boolean>;
  archived: Maybe<boolean>;
  new: Maybe<boolean>;
  featured: Maybe<boolean>;
  restricted: Maybe<boolean>;
  isTemplate: Maybe<boolean>;
  templateVariables: Maybe<string>;
  publishedAt: Maybe<string>;
  createdBy: Maybe<string>;
  updatedBy: Maybe<string>;
  createdAt: Datetime;
  updatedAt: Datetime;
  commentsEnabled: Maybe<boolean>;
  imageOptimized: Maybe<ImageOptimized>;
  iconOptimized: Maybe<ImageOptimized>;
  headerImageOptimized: Maybe<ImageOptimized>;
};

export type Template = {
  id: string;
  eventTitle: Maybe<string>;
  eventSlug: Maybe<string>;
  eventImage: Maybe<string>;
  marketTitle: Maybe<string>;
  description: Maybe<string>;
  resolutionSource: Maybe<string>;
  negRisk: Maybe<boolean>;
  sortBy: Maybe<string>;
  showMarketImages: Maybe<boolean>;
  seriesSlug: Maybe<string>;
  outcomes: Maybe<string>;
};

export type EventCreator = {
  id: string;
  creatorName: Maybe<string>;
  creatorHandle: Maybe<string>;
  creatorUrl: Maybe<string>;
  creatorImage: Maybe<string>;
  createdAt: Datetime;
  updatedAt: Datetime;
};

export type ClobReward = unknown;
